### ISSUE TITLE
Simplify import path

### ISSUE THREAD

**Issue by DeadlySurgeon** [AzureAD/microsoft-authentication-library-for-go#212]
The import path is rather long and very non golang like. Is there any simplification that can be done to the repo name for the next version, or at the very least move the packages out of `apps` as that is not a good import path?

Thanks!

**Comment by element-of-surprise** [comment]
You are correct, the import path is not Go like.  Non-lowercase words, hyphenated, etc....  

However it is consistent with the naming convention that AzureAD is using fo its other msal packages:

microsoft-authentication-library-for-dotnet
microsoft-authentication-library-for-js
microsoft-authentication-library-for-android
...

Normally, "app" like "common" is a bad, but like panics() not every use is bad.  Documentation and others label these as "apss" in the MSAL.  

While I would personally prefer: "azure/ad/go/msal", that is unlikely to be an option due to a need to be consistent for discovery and a bunch of other things.  A lot of these structures and conventions were put in years ago and are named in a .Net/Java like naming structure which lacks the brevity that we Go programmers like.

Sorry about this.  We will keep this in mind as we move towards v1, but this is unlikely to happen.
