### ISSUE TITLE
Replace usage of archived dependency: github.com/dgrijalva/jwt-go

### ISSUE THREAD

**Issue by abhidnya13** [AzureAD/microsoft-authentication-library-for-go#244]
Looks like github.com/dgrijalva/jwt-go has moved to a new location - https://github.com/golang-jwt/jwt
Refer : https://github.com/dgrijalva/jwt-go/issues/462

Update to use the newer location.
CC: @element-of-surprise

**Comment by henrik-me** [comment]
Marking as bug as the dependency is archived. Can also investigate if there are other libraries which better fit the bill and which are better maintained.

**Comment by element-of-surprise** [comment]
We should move, but its not a rush.  The other is a clone because the maintainer just couldn't keep up.  But I think for the moment each are mirroring each other.

This brings up the something we should consider, which is having some type of cadence for looking at our dependencies and evaluating if there are any benefits for moving to a new version.  Often the upgrades have no value and its better to stay with what works.  But maybe something is twice as fast or security problems...



John Doak
Manager, Change Management SRE
***@***.***
________________________________
