### ISSUE TITLE
[Bug] Interactive authentication can't redirect to https://localhost

### ISSUE THREAD

**Issue by chlowell** [AzureAD/microsoft-authentication-library-for-go#281]
The local redirect server hardcodes the `http` scheme, making interactive authentication impossible for an application that has registered `https://localhost` and not `http://localhost`:
https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/bf97c14840a7c721f4e9af2f421e57fdca561351/apps/internal/local/server.go#L85-L88

But I doubt that's a common scenario. If you're reading this and it's your scenario, please +1 this issue.

**Comment by bgavrilMS** [comment]
"https://localhost" in a public client app is a no-go because: 

- it'd require some sort of (self-signed?) certificate to be installed on the client machine. This is a public client (think Office), so it's not appropriate to install certs.
- "http://localhost" has special meaning in AAD - it means ANY local port. This allows MSAL to find a free port use it as redirect URI. Otherwise the app developer would have to specify a free port.

**Comment by bgavrilMS** [comment]
I think this is a known limitation of desktop apps. http://localhost is just an alias for a local socket.
