### ISSUE TITLE
Add support for on-behalf-of flow 

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-go#29]
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow

**Comment by henrik-me** [comment]
@abhidnya13, MSAL .NET is currently looking at providing out of the box performant token caching and partitioning for obo (work on the app cache is also done/in progress). We should ensure those improvements are also added to the cache story for obo here. 
CC: @bgavrilMS who can help with what/how/where etc.

**Comment by bgavrilMS** [comment]
yes, we will update the API review docs on how to efficiently partition MSAL's internal cache. But if you need to work on this ASAP, please contact me or @pmaytak and we can discuss. 

The summary of the changes are: 

- today, we store tokens in memory in maps, e.g. at_key -> at_payload
- this is not efficient when you have a lot of tokens and need to find a single 1
- the problem is partially solved by SuggestedCacheKey, i.e. MSAL helps app developers use a distributed cache
- many app developers do not want to use a distributed cache, for example for low traffic apps or for client_credentails
- proposal is to store tokens like map[partition_key] -> [map[token_key]-> token], where the partition key is:  tenant_id for client_creds; obo_assertion_hash for OBO, home_account_id for everything else
