### ISSUE TITLE
Get error: ClientCertificateCredential: unable to resolve an endpoint: server response error:

### ISSUE THREAD

**Issue by mingqishao** [AzureAD/microsoft-authentication-library-for-go#352]
We are using azidentity@v1.10 which depend on microsoft-authentication-library-for-go@v0.5.1. We occasionally get error `ClientCertificateCredential: unable to resolve an endpoint: server response error:`. Below is the full detail error message. We setup timeout in the azure client. This error should be from microsoft-authentication-library-for-go SDK and always occurs with timeout. So my questions are:

1. Why the endpoint in this message is empty? what is the endpoint, is the AAD authentication endpoint? We setup the AAD configuration at first time and never change it.
2. How could I customize the http client using by microsoft-authentication-library-for-go SDK? I want to add more trace in the http client, to see where the codes spend long time. 

```
failed to get managed cluster for validation. managed cluster ID: /subscriptions/3cbab75e-80cd-4daf-ad17-9b471f536ec9/resourceGroups/FL_e2erg-e2emtrcs-gfaiwJZyoWAxaZa_fleet-1_westcentralus/providers/Microsoft.ContainerService/managedClusters/hub. err: failed to get managed cluster. resource group: FL_e2erg-e2emtrcs-gfaiwJZyoWAxaZa_fleet-1_westcentralus. cluster name: hub. err: ClientCertificateCredential: unable to resolve an endpoint: server response error:
 context deadline exceeded
```

**Comment by chlowell** [comment]
## Short answers

> 1. Why the endpoint in this message is empty? what is the endpoint, is the AAD authentication endpoint?

The endpoint simply isn't included in the error, which MSAL (microsoft-authentication-library) received from `context`. In this case I doubt it's interesting (see below).

> 2. How could I customize the http client using by microsoft-authentication-library-for-go SDK?
> 

There are simpler ways to debug this error (see below) but here's how you can replace the HTTP client of an `azidentity` credential (Azure SDK clients have the same API):

```go
import (
	"net/http"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
)

client := http.Client{
	// customize the client however you like
}
options := azidentity.ClientCertificateCredentialOptions{ClientOptions: azcore.ClientOptions{Transport: &client}}
cred, err := azidentity.NewClientCertificateCredential(tenantID, clientID, certs, key, &options)
```

## Long answer
You may just need to increase the timeout, at least for initial client requests. An `azidentity` credential's first authentication takes much longer than its average authentication because MSAL sends two metadata requests before the first token request. The error message you shared indicates one of these metadata requests was in progress when the context reached its deadline. Which one specifically timed out probably isn't interesting, but you can determine that by enabling Azure SDK logging. `azidentity` credentials send MSAL's requests through an Azure SDK pipeline with built-in logging. Setting `AZURE_SDK_GO_LOGGING=all` enables all logs. There's also a programmatic API for more granular control:
```go
import (
	"fmt"
	azlog "github.com/Azure/azure-sdk-for-go/sdk/azcore/log"
)

// log HTTP requests and responses to console
azlog.SetEvents(azlog.EventRequest, azlog.EventResponse)
azlog.SetListener(func(e azlog.Event, s string) {
	fmt.Print(s)
})
```

**Comment by serbrech** [comment]
Thanks @chlowell, we'll apply our common client options to the azidentity options too.

On another somewhat related topic, I recall that there was some chats about providing caching at the azidentity layer, so that sharing the identity across multiple clients would not cause more calls than necessary. is that somewhere on the roadmap?
IMDS throttling is a serious concern for large RPs and we've battled it more than once with the track1 sdk with custom token providers...

**Comment by chlowell** [comment]
Yes. Managed identity token caching is implemented on our main branch, which will ship next week as 1.2.0-beta.3. (Just to be clear for anyone else reading this, all other credential types cache tokens already, as do Azure SDK clients.)

**Comment by mingqishao** [comment]
@chlowell,

Thank you for the information. I will close this issue.
