### ISSUE TITLE
[Bug] msal cache incompatiblity between v1.0 and  v1.1

### ISSUE THREAD

**Issue by weikanglim** [AzureAD/microsoft-authentication-library-for-go#453]
Public client. User authenticates interactively with device-code/authcode. Tokens are stored in a filesystem-based cache-backing, with subsequent operations relying on silent auth based on the token cache. 

Problem:
After refresh token expires, silent auth is now failing for users even after logging in due to stale token entries.

Description from @chlowell that best captures this:

In #425 that was released with v1.1, the cache entries are now lower-case keyed with is different than v1.0. Because v1.1 writes different keys than v1.0, this is now possible:

1. cache a refresh token for some account with v1.0
2. upgrade to v1.1
3. cache a new refresh token for that account

Now you have two refresh tokens cached for the same account. Which one MSAL uses depends on the iteration order of the map in which it stores the cache. Go doesn't specify that order or guarantee its consistency. So, whenever v1.1 iterates the map looking for a refresh token, it may find the v1.0 token, which will eventually be invalid because v1.1 never updates it. Silent authentication is then flaky so long as the v1.0 token remains in the cache. The solution is to purge the cache or at least the associated account.

## User Impact

1. User has a non-MFA token in the cache and uses MSAL GO 1.0
2. User upgrades to use MSAL GO 1.1
3. Tenant admin now requires MFA or user changes password
4. AAD will ask the user to login interactively  (e.g. to perform MFA)
5. a new MFA-RT is put in the cache, alongside the old nonMFA-RT (due to the bug)
6. **After 1h**, the AT expires and MSAL Go tries to refresh the RT. It incorrectly chooses the nonMFA-RT due to this bug.
7. User is prompted again - goto 4

**Comment by bgavrilMS** [comment]
@chlowell I was thinking about this some more. There are 2 situations that should be considered:

1. Apps that use MSAL GO 1.0 and have cache keys with uppercase
2. Apps that use MSAL Go 1.0 and migrate to MSAL Go 1.1 and have a mix of lowercase and upppercase


I can think of 2 fixes: 

# 1. Compact on read / write

- on cache read (Replace / Unmarshal), compact the dictionaries i.e. 
-- if 2 AccessTokens with the "same" key exist, prefer the lowercase one (as it's newer, coming from GO 1.1). Remove the other one. Repeat for RefreshTokens, IdTokens, Accounts etc.

- on cache write, compact the cache again

# 2. Deal with it at during cache filtering operation

e.g. [here](https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/e6db30a3d8987c8b09030969725208d3ca5a84bb/apps/internal/base/internal/storage/storage.go#L262)

i.e. modify that logic so that instead of returning the **first valid token**, it look at all tokens that match the criteria and:

- if 1 token is found matching the criteria, return it
- if 2 tokens exist but have the "same" key, remove MSAL GO 1.0 token and return MSAL GO 1.1 token
- otherwise panic, MSAL's internal cache is broken 

I am not sure which one is better from a perf perspective, i.e. if there are 1000s of tokens in the cache (partioned cache?), how will all this work? Public client and single tenant client_credentials can only have a handful of tokens, so perf implications are irrelevant.

**Comment by chlowell** [comment]
We could use the relation between v1.0 and v1.1 cache keys to implement a lazy solution 2 that upgrades the cache one key at a time as necessary. So, when search finds a matching token:
1. if it has a v1.1 key, we're done: return the token
2. if it has a v1.0 key, lowercase that key and use it to lookup the corresponding v1.1 token
3. if there's no v1.1 token, add one i.e. add the v1.0 token with a v1.1 key
4. remove the v1.0 token
5. return the v1.1 token

What do you think? I believe that's as performant as it gets, assuming the solution must be robust against unusual scenarios like v1.0 and v1.1 sharing a cache. If we aren't worried about scenarios like that, or it's okay to make users reauthenticate, I imagine we could do better by simply purging all v1.0 data after the first read.

**Comment by bgavrilMS** [comment]
Yes, that's very elegant. 

I would still propose to update the item finding logic to throw exception if 2+ candidates are found, but agree that this is somewhat orthogonal.
